name: CI/CD for MERN Stack with Render

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use your preferred Node.js version

      # Backend build & test
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      

      # Frontend build & test
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      

      # Deploy to Render using Deploy Hooks
      - name: Trigger Render Deployment
        env:
          RENDER_DEPLOY_HOOK_BACKEND: ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}
          RENDER_DEPLOY_HOOK_FRONTEND: ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
        run: |
          curl -X POST $RENDER_DEPLOY_HOOK_BACKEND
          curl -X POST $RENDER_DEPLOY_HOOK_FRONTEND
